export const rows = [
    {
        id: 0,
        type: 'default_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 1,
        type: 'default_mix_highincome',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 2,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 3,
        type: 'low1_density_mix_highincome',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 4,
        type: 'low2_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 5,
        type: 'low2_density_mix_highincome',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 6,
        type: 'low3_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 7,
        type: 'low3_density_mix_highincome',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 8,
        type: 'low4_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 9,
        type: 'low4_density_mix_highincome',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 10,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 11,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 12,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 13,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 14,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 15,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 16,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 17,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 18,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 19,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 20,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 21,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 22,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 23,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 24,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 25,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 26,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 27,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
    {
        id: 28,
        type: 'low1_density_mix',
        res_density: '',
        far: '',
        '102_pcnt': '',
        '201_pcnt': '',
        '202_pcnt': '',
        '204_pcnt': '',
        '205_pcnt': '',
        '301_pcnt': '',
        '401_pcnt': '',
        '502_pcnt': '',
        '505_pcnt': '',
        '507_pcnt': '',
        '601_pcnt': '',
        '605_pcnt': '',
        '610_pcnt': '',
        '701_pcnt': '',
        '705_pcnt': '',
        '730_pcnt': '',
        '801_pcnt': '',
        '901_pcnt': '',
        '902_pcnt': '',
        '903_pcnt': '',
        '1001_pcnt': '',
        '1101_pcnt': '',
        '1201_pcnt': '',
        '102_land_sqm_per_unit': '',
        '201_land_sqm_per_unit': '',
        '202_land_sqm_per_unit': '',
        '204_land_sqm_per_unit': '',
        '205_land_sqm_per_unit': '',
        '401_land_sqm_per_unit': '',
        '502_land_sqm_per_unit': '',
        '505_land_sqm_per_unit': '',
        '507_land_sqm_per_unit': '',
        '601_land_sqm_per_unit': '',
        '605_land_sqm_per_unit': '',
        '610_land_sqm_per_unit': '',
        '701_land_sqm_per_unit': '',
        '705_land_sqm_per_unit': '',
        '730_land_sqm_per_unit': '',
        '801_land_sqm_per_unit': '',
        '901_land_sqm_per_unit': '',
        '902_land_sqm_per_unit': '',
        '903_land_sqm_per_unit': '',
        '1001_land_sqm_per_unit': '',
        '1101_land_sqm_per_unit': '',
        '1201_land_sqm_per_unit': '',
    },
]



// const valueSetter = (params) => {
//     const newValue = params.newValue;
//     const field = params.colDef.field;
//     const id = params.id;
//     const data = [...params.api.getDisplayedRowAtIndex(id).data];
//     data[field] = newValue;
//     params.api.applyTransaction({ update: [data] });
//     return true;

// }
export const columns = [
    {
        field: 'type',
        //headerName: 'Building Type',
        //width: 240,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //cellClassName: 'super-app-theme--cell',
    },
    {
        field: 'far',
        //renderHeader: () => {
        //                    return <strong>{'Floor Area Ratio'}</strong>
        // },
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //cellClassName: 'super-app-theme--cell',
    },
    {
        field: 'res_density',
        // renderHeader: () => {
        //     return <strong>{'Residential Density'}</strong>
        // },
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //cellClassName: 'super-app-theme--cell',
    },
    {
        field: '102_pcnt',
        // renderHeader: () => {
        //     return <strong>{'102 Percent'}</strong>
        // },
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '201_pcnt',
        // renderHeader: () => {
        //     return <strong>{'201 Percent'}</strong>
        // },
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '202_pcnt',
        // renderHeader: () => {
        //     return <strong>{'202 Percent'}</strong>
        // },
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '204_pcnt',
        // renderHeader: () => {
        //     return <strong>{'204 Percent'}</strong>
        // },
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '205_pcnt',
        // renderHeader: () => {
        //     return <strong>{'205 Percent'}</strong>
        // },
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '301_pcnt',
        // renderHeader: () => {
        //     return <strong>{'301 Percent'}</strong>
        // },
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '401_pcnt',
        //headerName: '401 Percent',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        // editable: true,
        // //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '502_pcnt',
        //headerName: '502 Percent',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '505_pcnt',
        //headerName: '505 Percent',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '507_pcnt',
        // //headerName: '507 Percent',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '601_pcnt',
        //headerName: '601 Percent',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '605_pcnt',
        //headerName: '605 Percent',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '610_pcnt',
        //headerName: '610 Percent',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '701_pcnt',
        //headerName: '701 Percent',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '705_pcnt',
        //headerName: '705 Percent',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '730_pcnt',
        //headerName: '730 Percent',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '801_pcnt',
        //headerName: '801 Percent',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '901_pcnt',
        //headerName: '901 Percent',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '902_pcnt',
        //headerName: '902 Percent',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '903_pcnt',
        //headerName: '903 Percent',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '1001_pcnt',
        //headerName: '1001 Percent',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '1101_pcnt',
        //headerName: '1101 Percent',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '1201_pcnt',
        //headerName: '1201 Percent',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '102_land_sqm_per_unit',
        //headerName: '102 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '201_land_sqm_per_unit',
        //headerName: '201 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '202_land_sqm_per_unit',
        //headerName: '202 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '204_land_sqm_per_unit',
        //headerName: '204 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '205_land_sqm_per_unit',
        //headerName: '205 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '401_land_sqm_per_unit',
        //headerName: '401 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        // editable: true,
        // //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '502_land_sqm_per_unit',
        //headerName: '502 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '505_land_sqm_per_unit',
        //headerName: '505 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '507_land_sqm_per_unit',
        //headerName: '507 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '601_land_sqm_per_unit',
        //headerName: '601 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '605_land_sqm_per_unit',
        //headerName: '605 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '610_land_sqm_per_unit',
        //headerName: '610 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '701_land_sqm_per_unit',
        //headerName: '701 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '705_land_sqm_per_unit',
        //headerName: '705 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '730_land_sqm_per_unit',
        //headerName: '730 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '801_land_sqm_per_unitd',
        //headerName: '801 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '901_land_sqm_per_unit',
        //headerName: '901 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '902_land_sqm_per_unit',
        //headerName: '902 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '903_land_sqm_per_unit',
        //headerName: '903 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '1001_land_sqm_per_unit',
        //headerName: '1001 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '1101_land_sqm_per_unit',
        //headerName: '1101 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
    {
        field: '1202_land_sqm_per_unit',
        //headerName: '1202 Land',
        //width: 150,
        //header//align: 'center',
        //align: 'center',
        editable: true,
        //renderEditCell: (params) => <CustomInput {...params} />,
    },
]



