name: Automated Build NICIS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install npm dependencies
        run: npm install
      - name: Run configure task
        run: python -c "import json;config = json.load(open('./src/config.json','r+')); config['api_base_url'] = ''; json.dump(config, open('./src/config.json','w'))"
      - name: Run build task
      - name: Push to deployment branch
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB}}
        with:
          source-directory: "build"
          destination-github-username: "lethuzulu"
          destination-repository-name: "builder"
          user-email: lethuzulu345@gmail.com
          create-target-branch-if-needed: true
          target-branch: deploy-nicis
          
